# pointing at Swagger's petstore docs so the example has some content
documentation:
  swagger:
    services:
      -
        name: Pet Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: Human Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: Zoo Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: Food Service
        url: http://petstore.swagger.io/v2/swagger.json
        version: 2.0
      -
        name: mini-program member
        url: /api/v1/one
        version: 2.0
server:
  port: 8091
